apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
  namespace: temporal
  labels:
    app: temporal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-worker
  template:
    metadata:
      labels:
        app: temporal-worker
    spec:
      containers:
      - name: temporal-worker
        image: ksiadz/temporal-worker:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: temporal-worker-config
        - secretRef:
            name: temporal-worker-secrets
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Environment variables:"
          env | grep TEMPORAL
          python3 worker.py
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          exec:
            command:
            - python3
            - -c
            - "import temporalio; print('OK')"
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python3
            - -c
            - "import temporalio; print('OK')"
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3 