apiVersion: v1
kind: Service
metadata:
  name: temporal-server
  namespace: temporal
  labels:
    app: temporal-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: temporal-server 