apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-worker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/jolly-hacker-sea-watcher
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: temporal-worker-secrets
      namespace: temporal
      jsonPointers:
        - /data 