apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-worker-secrets
  namespace: temporal
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: temporal-worker-secrets
    creationPolicy: Owner
  data:
  - secretKey: TEMPORAL_API_KEY
    remoteRef:
      key: temporal/api-key
      property: value 