apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jolly-hacker-sea-watcher
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/irregularchat/jolly-hacker-sea-watcher
  ref:
    branch: main
  # secretRef:
    # name: github-credentials 