# For private repositories, we need to use a secret to store the credentials.
# apiVersion: v1
# kind: Secret
# metadata:
#   name: github-credentials
#   namespace: flux-system
# type: Opaque
# stringData:
#   username: your-github-username
#   password: your-github-token 